// <auto-generated />
// DO NOT MODIFY THIS FILE

// Changes can be made in a corresponding partial file, or by changing
// the template in <root>/generation/templates and generating the class again.


using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace ShipEngineSDK;

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public partial interface IShipEngine
{
    /// <summary>
    /// Create an Account Image Create an Account Image
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="createAccountSettingsImageRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsImagesResponseBody)</returns>
    Task<ShipEngineResponse<GetAccountSettingsImagesResponseBody>> CreateAccountImage(CreateAccountSettingsImageRequestBody createAccountSettingsImageRequestBody, CancellationToken cancellationToken = default);

    /// <summary>
    /// Create an Account Image Create an Account Image
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="createAccountSettingsImageRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsImagesResponseBody)</returns>
    Task<ShipEngineResponse<GetAccountSettingsImagesResponseBody>> CreateAccountImage(HttpClient methodClient, CreateAccountSettingsImageRequestBody createAccountSettingsImageRequestBody, CancellationToken cancellationToken = default);

    /// <summary>
    /// Delete Account Image By Id Delete Account Image By Id
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (string)</returns>
    Task<ShipEngineResponse<string>> DeleteAccountImageById(string labelImageId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Delete Account Image By Id Delete Account Image By Id
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (string)</returns>
    Task<ShipEngineResponse<string>> DeleteAccountImageById(HttpClient methodClient, string labelImageId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get Account Image By ID Retrieve information for an account image.
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsImagesResponseBody)</returns>
    Task<ShipEngineResponse<GetAccountSettingsImagesResponseBody>> GetAccountSettingsImagesById(string labelImageId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get Account Image By ID Retrieve information for an account image.
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsImagesResponseBody)</returns>
    Task<ShipEngineResponse<GetAccountSettingsImagesResponseBody>> GetAccountSettingsImagesById(HttpClient methodClient, string labelImageId, CancellationToken cancellationToken = default);

    /// <summary>
    /// List Account Images List all account images for the ShipEngine account
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (ListAccountSettingsImagesResponseBody)</returns>
    Task<ShipEngineResponse<ListAccountSettingsImagesResponseBody>> ListAccountImages(CancellationToken cancellationToken = default);

    /// <summary>
    /// List Account Images List all account images for the ShipEngine account
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (ListAccountSettingsImagesResponseBody)</returns>
    Task<ShipEngineResponse<ListAccountSettingsImagesResponseBody>> ListAccountImages(HttpClient methodClient, CancellationToken cancellationToken = default);

    /// <summary>
    /// List Account Settings List all account settings for the ShipEngine account
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsResponseBody)</returns>
    Task<ShipEngineResponse<GetAccountSettingsResponseBody>> ListAccountSettings(CancellationToken cancellationToken = default);

    /// <summary>
    /// List Account Settings List all account settings for the ShipEngine account
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsResponseBody)</returns>
    Task<ShipEngineResponse<GetAccountSettingsResponseBody>> ListAccountSettings(HttpClient methodClient, CancellationToken cancellationToken = default);

    /// <summary>
    /// Update Account Image By ID Update information for an account image.
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="updateAccountSettingsImageRequestBody"></param>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (string)</returns>
    Task<ShipEngineResponse<string>> UpdateAccountSettingsImagesById(UpdateAccountSettingsImageRequestBody updateAccountSettingsImageRequestBody, string labelImageId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Update Account Image By ID Update information for an account image.
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="updateAccountSettingsImageRequestBody"></param>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (string)</returns>
    Task<ShipEngineResponse<string>> UpdateAccountSettingsImagesById(HttpClient methodClient, UpdateAccountSettingsImageRequestBody updateAccountSettingsImageRequestBody, string labelImageId, CancellationToken cancellationToken = default);

}

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public partial class ShipEngine
{
    /// <summary>
    /// Create an Account Image Create an Account Image
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="createAccountSettingsImageRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsImagesResponseBody)</returns>
    public Task<ShipEngineResponse<GetAccountSettingsImagesResponseBody>> CreateAccountImage(CreateAccountSettingsImageRequestBody createAccountSettingsImageRequestBody, CancellationToken cancellationToken = default)
    {
        return CreateAccountImage(_client, createAccountSettingsImageRequestBody, cancellationToken);
    }

    /// <summary>
    /// Create an Account Image Create an Account Image
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="createAccountSettingsImageRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsImagesResponseBody)</returns>
    public async Task<ShipEngineResponse<GetAccountSettingsImagesResponseBody>> CreateAccountImage(HttpClient methodClient, CreateAccountSettingsImageRequestBody createAccountSettingsImageRequestBody, CancellationToken cancellationToken = default)
    {
        // verify the required parameter 'createAccountSettingsImageRequestBody' is set
        if (createAccountSettingsImageRequestBody == null)
        {
            throw new ArgumentNullException(nameof(createAccountSettingsImageRequestBody));
        }


        RequestOptions requestOptions = new("/v1/account/settings/images");

        requestOptions.Data = JsonSerializer.Serialize(createAccountSettingsImageRequestBody, JsonSerializerOptions);

        requestOptions.Operation = "AccountApi.CreateAccountImage";

        var (data, response) = await GetHttpResponse<GetAccountSettingsImagesResponseBody>(HttpMethods.Post, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<GetAccountSettingsImagesResponseBody>(data, response.StatusCode, headers);
    }

    /// <summary>
    /// Delete Account Image By Id Delete Account Image By Id
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (string)</returns>
    public Task<ShipEngineResponse<string>> DeleteAccountImageById(string labelImageId, CancellationToken cancellationToken = default)
    {
        return DeleteAccountImageById(_client, labelImageId, cancellationToken);
    }

    /// <summary>
    /// Delete Account Image By Id Delete Account Image By Id
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (string)</returns>
    public async Task<ShipEngineResponse<string>> DeleteAccountImageById(HttpClient methodClient, string labelImageId, CancellationToken cancellationToken = default)
    {
        // verify the required parameter 'labelImageId' is set
        if (labelImageId == null)
        {
            throw new ArgumentNullException(nameof(labelImageId));
        }


        RequestOptions requestOptions = new("/v1/account/settings/images/{label_image_id}");

        requestOptions.PathParameters.Add("label_image_id", ClientUtils.ParameterToString(labelImageId)); // path parameter

        requestOptions.Operation = "AccountApi.DeleteAccountImageById";

        var (data, response) = await GetHttpResponse<string>(HttpMethods.Delete, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<string>(data, response.StatusCode, headers);
    }

    /// <summary>
    /// Get Account Image By ID Retrieve information for an account image.
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsImagesResponseBody)</returns>
    public Task<ShipEngineResponse<GetAccountSettingsImagesResponseBody>> GetAccountSettingsImagesById(string labelImageId, CancellationToken cancellationToken = default)
    {
        return GetAccountSettingsImagesById(_client, labelImageId, cancellationToken);
    }

    /// <summary>
    /// Get Account Image By ID Retrieve information for an account image.
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsImagesResponseBody)</returns>
    public async Task<ShipEngineResponse<GetAccountSettingsImagesResponseBody>> GetAccountSettingsImagesById(HttpClient methodClient, string labelImageId, CancellationToken cancellationToken = default)
    {
        // verify the required parameter 'labelImageId' is set
        if (labelImageId == null)
        {
            throw new ArgumentNullException(nameof(labelImageId));
        }


        RequestOptions requestOptions = new("/v1/account/settings/images/{label_image_id}");

        requestOptions.PathParameters.Add("label_image_id", ClientUtils.ParameterToString(labelImageId)); // path parameter

        requestOptions.Operation = "AccountApi.GetAccountSettingsImagesById";

        var (data, response) = await GetHttpResponse<GetAccountSettingsImagesResponseBody>(HttpMethods.Get, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<GetAccountSettingsImagesResponseBody>(data, response.StatusCode, headers);
    }

    /// <summary>
    /// List Account Images List all account images for the ShipEngine account
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (ListAccountSettingsImagesResponseBody)</returns>
    public Task<ShipEngineResponse<ListAccountSettingsImagesResponseBody>> ListAccountImages(CancellationToken cancellationToken = default)
    {
        return ListAccountImages(_client, cancellationToken);
    }

    /// <summary>
    /// List Account Images List all account images for the ShipEngine account
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (ListAccountSettingsImagesResponseBody)</returns>
    public async Task<ShipEngineResponse<ListAccountSettingsImagesResponseBody>> ListAccountImages(HttpClient methodClient, CancellationToken cancellationToken = default)
    {

        RequestOptions requestOptions = new("/v1/account/settings/images");


        requestOptions.Operation = "AccountApi.ListAccountImages";

        var (data, response) = await GetHttpResponse<ListAccountSettingsImagesResponseBody>(HttpMethods.Get, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<ListAccountSettingsImagesResponseBody>(data, response.StatusCode, headers);
    }

    /// <summary>
    /// List Account Settings List all account settings for the ShipEngine account
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsResponseBody)</returns>
    public Task<ShipEngineResponse<GetAccountSettingsResponseBody>> ListAccountSettings(CancellationToken cancellationToken = default)
    {
        return ListAccountSettings(_client, cancellationToken);
    }

    /// <summary>
    /// List Account Settings List all account settings for the ShipEngine account
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetAccountSettingsResponseBody)</returns>
    public async Task<ShipEngineResponse<GetAccountSettingsResponseBody>> ListAccountSettings(HttpClient methodClient, CancellationToken cancellationToken = default)
    {

        RequestOptions requestOptions = new("/v1/account/settings");


        requestOptions.Operation = "AccountApi.ListAccountSettings";

        var (data, response) = await GetHttpResponse<GetAccountSettingsResponseBody>(HttpMethods.Get, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<GetAccountSettingsResponseBody>(data, response.StatusCode, headers);
    }

    /// <summary>
    /// Update Account Image By ID Update information for an account image.
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="updateAccountSettingsImageRequestBody"></param>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (string)</returns>
    public Task<ShipEngineResponse<string>> UpdateAccountSettingsImagesById(UpdateAccountSettingsImageRequestBody updateAccountSettingsImageRequestBody, string labelImageId, CancellationToken cancellationToken = default)
    {
        return UpdateAccountSettingsImagesById(_client, updateAccountSettingsImageRequestBody, labelImageId, cancellationToken);
    }

    /// <summary>
    /// Update Account Image By ID Update information for an account image.
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="updateAccountSettingsImageRequestBody"></param>
    /// <param name="labelImageId">Label Image Id</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (string)</returns>
    public async Task<ShipEngineResponse<string>> UpdateAccountSettingsImagesById(HttpClient methodClient, UpdateAccountSettingsImageRequestBody updateAccountSettingsImageRequestBody, string labelImageId, CancellationToken cancellationToken = default)
    {
        // verify the required parameter 'updateAccountSettingsImageRequestBody' is set
        if (updateAccountSettingsImageRequestBody == null)
        {
            throw new ArgumentNullException(nameof(updateAccountSettingsImageRequestBody));
        }

        // verify the required parameter 'labelImageId' is set
        if (labelImageId == null)
        {
            throw new ArgumentNullException(nameof(labelImageId));
        }


        RequestOptions requestOptions = new("/v1/account/settings/images/{label_image_id}");

        requestOptions.PathParameters.Add("label_image_id", ClientUtils.ParameterToString(labelImageId)); // path parameter
        requestOptions.Data = JsonSerializer.Serialize(updateAccountSettingsImageRequestBody, JsonSerializerOptions);

        requestOptions.Operation = "AccountApi.UpdateAccountSettingsImagesById";

        var (data, response) = await GetHttpResponse<string>(HttpMethods.Put, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<string>(data, response.StatusCode, headers);
    }

}
