// <auto-generated />
// DO NOT MODIFY THIS FILE

// Changes can be made in a corresponding partial file, or by changing
// the template in <root>/generation/templates and generating the class again.


using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace ShipEngineSDK;

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public partial interface IShipEngine
{
    /// <summary>
    /// Get Shipping Rates It&#39;s not uncommon that you want to give your customer the choice between whether they want to ship the fastest, cheapest, or the most trusted route. Most companies don&#39;t solely ship things using a single shipping option; so we provide functionality to show you all your options! 
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="calculateRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (CalculateRatesResponseBody)</returns>
    Task<ShipEngineResponse<CalculateRatesResponseBody>> CalculateRates(CalculateRatesRequestBody calculateRatesRequestBody, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get Shipping Rates It&#39;s not uncommon that you want to give your customer the choice between whether they want to ship the fastest, cheapest, or the most trusted route. Most companies don&#39;t solely ship things using a single shipping option; so we provide functionality to show you all your options! 
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="calculateRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (CalculateRatesResponseBody)</returns>
    Task<ShipEngineResponse<CalculateRatesResponseBody>> CalculateRates(HttpClient methodClient, CalculateRatesRequestBody calculateRatesRequestBody, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get Bulk Rates Get Bulk Shipment Rates
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="compareBulkRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (List&lt;BulkRate&gt;)</returns>
    Task<ShipEngineResponse<List<BulkRate>>> CompareBulkRates(CompareBulkRatesRequestBody compareBulkRatesRequestBody, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get Bulk Rates Get Bulk Shipment Rates
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="compareBulkRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (List&lt;BulkRate&gt;)</returns>
    Task<ShipEngineResponse<List<BulkRate>>> CompareBulkRates(HttpClient methodClient, CompareBulkRatesRequestBody compareBulkRatesRequestBody, CancellationToken cancellationToken = default);

    /// <summary>
    /// Estimate Rates Get Rate Estimates
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="estimateRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (List&lt;RateEstimate&gt;)</returns>
    Task<ShipEngineResponse<List<RateEstimate>>> EstimateRates(EstimateRatesRequestBody estimateRatesRequestBody, CancellationToken cancellationToken = default);

    /// <summary>
    /// Estimate Rates Get Rate Estimates
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="estimateRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (List&lt;RateEstimate&gt;)</returns>
    Task<ShipEngineResponse<List<RateEstimate>>> EstimateRates(HttpClient methodClient, EstimateRatesRequestBody estimateRatesRequestBody, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get Rate By ID Retrieve a previously queried rate by its ID
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="rateId">Rate ID</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetRateByIdResponseBody)</returns>
    Task<ShipEngineResponse<GetRateByIdResponseBody>> GetRateById(string rateId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Get Rate By ID Retrieve a previously queried rate by its ID
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="rateId">Rate ID</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetRateByIdResponseBody)</returns>
    Task<ShipEngineResponse<GetRateByIdResponseBody>> GetRateById(HttpClient methodClient, string rateId, CancellationToken cancellationToken = default);

}

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public partial class ShipEngine
{
    /// <summary>
    /// Get Shipping Rates It&#39;s not uncommon that you want to give your customer the choice between whether they want to ship the fastest, cheapest, or the most trusted route. Most companies don&#39;t solely ship things using a single shipping option; so we provide functionality to show you all your options! 
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="calculateRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (CalculateRatesResponseBody)</returns>
    public Task<ShipEngineResponse<CalculateRatesResponseBody>> CalculateRates(CalculateRatesRequestBody calculateRatesRequestBody, CancellationToken cancellationToken = default)
    {
        return CalculateRates(_client, calculateRatesRequestBody, cancellationToken);
    }

    /// <summary>
    /// Get Shipping Rates It&#39;s not uncommon that you want to give your customer the choice between whether they want to ship the fastest, cheapest, or the most trusted route. Most companies don&#39;t solely ship things using a single shipping option; so we provide functionality to show you all your options! 
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="calculateRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (CalculateRatesResponseBody)</returns>
    public async Task<ShipEngineResponse<CalculateRatesResponseBody>> CalculateRates(HttpClient methodClient, CalculateRatesRequestBody calculateRatesRequestBody, CancellationToken cancellationToken = default)
    {
        // verify the required parameter 'calculateRatesRequestBody' is set
        if (calculateRatesRequestBody == null)
        {
            throw new ArgumentNullException(nameof(calculateRatesRequestBody));
        }


        RequestOptions requestOptions = new("/v1/rates");

        requestOptions.Data = JsonSerializer.Serialize(calculateRatesRequestBody, JsonSerializerOptions);

        requestOptions.Operation = "RatesApi.CalculateRates";

        var (data, response) = await GetHttpResponse<CalculateRatesResponseBody>(HttpMethods.Post, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<CalculateRatesResponseBody>(data, response.StatusCode, headers);
    }

    /// <summary>
    /// Get Bulk Rates Get Bulk Shipment Rates
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="compareBulkRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (List&lt;BulkRate&gt;)</returns>
    public Task<ShipEngineResponse<List<BulkRate>>> CompareBulkRates(CompareBulkRatesRequestBody compareBulkRatesRequestBody, CancellationToken cancellationToken = default)
    {
        return CompareBulkRates(_client, compareBulkRatesRequestBody, cancellationToken);
    }

    /// <summary>
    /// Get Bulk Rates Get Bulk Shipment Rates
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="compareBulkRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (List&lt;BulkRate&gt;)</returns>
    public async Task<ShipEngineResponse<List<BulkRate>>> CompareBulkRates(HttpClient methodClient, CompareBulkRatesRequestBody compareBulkRatesRequestBody, CancellationToken cancellationToken = default)
    {
        // verify the required parameter 'compareBulkRatesRequestBody' is set
        if (compareBulkRatesRequestBody == null)
        {
            throw new ArgumentNullException(nameof(compareBulkRatesRequestBody));
        }


        RequestOptions requestOptions = new("/v1/rates/bulk");

        requestOptions.Data = JsonSerializer.Serialize(compareBulkRatesRequestBody, JsonSerializerOptions);

        requestOptions.Operation = "RatesApi.CompareBulkRates";

        var (data, response) = await GetHttpResponse<List<BulkRate>>(HttpMethods.Post, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<List<BulkRate>>(data, response.StatusCode, headers);
    }

    /// <summary>
    /// Estimate Rates Get Rate Estimates
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="estimateRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (List&lt;RateEstimate&gt;)</returns>
    public Task<ShipEngineResponse<List<RateEstimate>>> EstimateRates(EstimateRatesRequestBody estimateRatesRequestBody, CancellationToken cancellationToken = default)
    {
        return EstimateRates(_client, estimateRatesRequestBody, cancellationToken);
    }

    /// <summary>
    /// Estimate Rates Get Rate Estimates
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="estimateRatesRequestBody"></param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (List&lt;RateEstimate&gt;)</returns>
    public async Task<ShipEngineResponse<List<RateEstimate>>> EstimateRates(HttpClient methodClient, EstimateRatesRequestBody estimateRatesRequestBody, CancellationToken cancellationToken = default)
    {
        // verify the required parameter 'estimateRatesRequestBody' is set
        if (estimateRatesRequestBody == null)
        {
            throw new ArgumentNullException(nameof(estimateRatesRequestBody));
        }


        RequestOptions requestOptions = new("/v1/rates/estimate");

        requestOptions.Data = JsonSerializer.Serialize(estimateRatesRequestBody, JsonSerializerOptions);

        requestOptions.Operation = "RatesApi.EstimateRates";

        var (data, response) = await GetHttpResponse<List<RateEstimate>>(HttpMethods.Post, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<List<RateEstimate>>(data, response.StatusCode, headers);
    }

    /// <summary>
    /// Get Rate By ID Retrieve a previously queried rate by its ID
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="rateId">Rate ID</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetRateByIdResponseBody)</returns>
    public Task<ShipEngineResponse<GetRateByIdResponseBody>> GetRateById(string rateId, CancellationToken cancellationToken = default)
    {
        return GetRateById(_client, rateId, cancellationToken);
    }

    /// <summary>
    /// Get Rate By ID Retrieve a previously queried rate by its ID
    /// </summary>
    /// <exception cref="System.ArgumentNullException">Thrown when required argument is null</exception>
    /// <exception cref="ShipEngineSDK.ShipEngineException">Thrown when fails to make API call</exception>
    /// <param name="methodClient">HttpClient to use for the request</param>
    /// <param name="rateId">Rate ID</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ShipEngineResponse (GetRateByIdResponseBody)</returns>
    public async Task<ShipEngineResponse<GetRateByIdResponseBody>> GetRateById(HttpClient methodClient, string rateId, CancellationToken cancellationToken = default)
    {
        // verify the required parameter 'rateId' is set
        if (rateId == null)
        {
            throw new ArgumentNullException(nameof(rateId));
        }


        RequestOptions requestOptions = new("/v1/rates/{rate_id}");

        requestOptions.PathParameters.Add("rate_id", ClientUtils.ParameterToString(rateId)); // path parameter

        requestOptions.Operation = "RatesApi.GetRateById";

        var (data, response) = await GetHttpResponse<GetRateByIdResponseBody>(HttpMethods.Get, requestOptions.FullPath(), requestOptions.Data, methodClient, _config, cancellationToken);
        var headers = response.Headers.ToDictionary(h => h.Key, h => h.Value.FirstOrDefault(),
            StringComparer.InvariantCultureIgnoreCase);
        return new ShipEngineResponse<GetRateByIdResponseBody>(data, response.StatusCode, headers);
    }

}
