/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing AddressValidationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressValidationResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressValidationResult
        //private AddressValidationResult instance;

        public AddressValidationResultTests()
        {
            // TODO uncomment below to create an instance of AddressValidationResult
            //instance = new AddressValidationResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressValidationResult
        /// </summary>
        [Fact]
        public void AddressValidationResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressValidationResult
            //Assert.IsType<AddressValidationResult>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'OriginalAddress'
        /// </summary>
        [Fact]
        public void OriginalAddressTest()
        {
            // TODO unit test for the property 'OriginalAddress'
        }

        /// <summary>
        /// Test the property 'MatchedAddress'
        /// </summary>
        [Fact]
        public void MatchedAddressTest()
        {
            // TODO unit test for the property 'MatchedAddress'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
    }

}