/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ConnectInsurerRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConnectInsurerRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConnectInsurerRequestBody
        //private ConnectInsurerRequestBody instance;

        public ConnectInsurerRequestBodyTests()
        {
            // TODO uncomment below to create an instance of ConnectInsurerRequestBody
            //instance = new ConnectInsurerRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConnectInsurerRequestBody
        /// </summary>
        [Fact]
        public void ConnectInsurerRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConnectInsurerRequestBody
            //Assert.IsType<ConnectInsurerRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'PolicyId'
        /// </summary>
        [Fact]
        public void PolicyIdTest()
        {
            // TODO unit test for the property 'PolicyId'
        }
    }

}