/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ConnectAsendiaRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConnectAsendiaRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConnectAsendiaRequestBody
        //private ConnectAsendiaRequestBody instance;

        public ConnectAsendiaRequestBodyTests()
        {
            // TODO uncomment below to create an instance of ConnectAsendiaRequestBody
            //instance = new ConnectAsendiaRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConnectAsendiaRequestBody
        /// </summary>
        [Fact]
        public void ConnectAsendiaRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConnectAsendiaRequestBody
            //Assert.IsType<ConnectAsendiaRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Fact]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }

        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }

        /// <summary>
        /// Test the property 'FtpUsername'
        /// </summary>
        [Fact]
        public void FtpUsernameTest()
        {
            // TODO unit test for the property 'FtpUsername'
        }

        /// <summary>
        /// Test the property 'FtpPassword'
        /// </summary>
        [Fact]
        public void FtpPasswordTest()
        {
            // TODO unit test for the property 'FtpPassword'
        }
    }

}