/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing CreateWebhookRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateWebhookRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateWebhookRequestBody
        //private CreateWebhookRequestBody instance;

        public CreateWebhookRequestBodyTests()
        {
            // TODO uncomment below to create an instance of CreateWebhookRequestBody
            //instance = new CreateWebhookRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateWebhookRequestBody
        /// </summary>
        [Fact]
        public void CreateWebhookRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateWebhookRequestBody
            //Assert.IsType<CreateWebhookRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Fact]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }
    }

}