/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing CreateManifestResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateManifestResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateManifestResponseBody
        //private CreateManifestResponseBody instance;

        public CreateManifestResponseBodyTests()
        {
            // TODO uncomment below to create an instance of CreateManifestResponseBody
            //instance = new CreateManifestResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateManifestResponseBody
        /// </summary>
        [Fact]
        public void CreateManifestResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateManifestResponseBody
            //Assert.IsType<CreateManifestResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'Manifests'
        /// </summary>
        [Fact]
        public void ManifestsTest()
        {
            // TODO unit test for the property 'Manifests'
        }

        /// <summary>
        /// Test the property 'ManifestRequests'
        /// </summary>
        [Fact]
        public void ManifestRequestsTest()
        {
            // TODO unit test for the property 'ManifestRequests'
        }

        /// <summary>
        /// Test the property 'ManifestId'
        /// </summary>
        [Fact]
        public void ManifestIdTest()
        {
            // TODO unit test for the property 'ManifestId'
        }

        /// <summary>
        /// Test the property 'FormId'
        /// </summary>
        [Fact]
        public void FormIdTest()
        {
            // TODO unit test for the property 'FormId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Fact]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }

        /// <summary>
        /// Test the property 'Shipments'
        /// </summary>
        [Fact]
        public void ShipmentsTest()
        {
            // TODO unit test for the property 'Shipments'
        }

        /// <summary>
        /// Test the property 'WarehouseId'
        /// </summary>
        [Fact]
        public void WarehouseIdTest()
        {
            // TODO unit test for the property 'WarehouseId'
        }

        /// <summary>
        /// Test the property 'SubmissionId'
        /// </summary>
        [Fact]
        public void SubmissionIdTest()
        {
            // TODO unit test for the property 'SubmissionId'
        }

        /// <summary>
        /// Test the property 'CarrierId'
        /// </summary>
        [Fact]
        public void CarrierIdTest()
        {
            // TODO unit test for the property 'CarrierId'
        }

        /// <summary>
        /// Test the property 'ManifestDownload'
        /// </summary>
        [Fact]
        public void ManifestDownloadTest()
        {
            // TODO unit test for the property 'ManifestDownload'
        }

        /// <summary>
        /// Test the property 'LabelIds'
        /// </summary>
        [Fact]
        public void LabelIdsTest()
        {
            // TODO unit test for the property 'LabelIds'
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }

}