/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorWithLabelIdResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorWithLabelIdResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorWithLabelIdResponseBody
        //private ErrorWithLabelIdResponseBody instance;

        public ErrorWithLabelIdResponseBodyTests()
        {
            // TODO uncomment below to create an instance of ErrorWithLabelIdResponseBody
            //instance = new ErrorWithLabelIdResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorWithLabelIdResponseBody
        /// </summary>
        [Fact]
        public void ErrorWithLabelIdResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorWithLabelIdResponseBody
            //Assert.IsType<ErrorWithLabelIdResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }

}