/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing LabelDownload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LabelDownloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LabelDownload
        //private LabelDownload instance;

        public LabelDownloadTests()
        {
            // TODO uncomment below to create an instance of LabelDownload
            //instance = new LabelDownload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LabelDownload
        /// </summary>
        [Fact]
        public void LabelDownloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" LabelDownload
            //Assert.IsType<LabelDownload>(instance);
        }

        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Fact]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

        /// <summary>
        /// Test the property 'Pdf'
        /// </summary>
        [Fact]
        public void PdfTest()
        {
            // TODO unit test for the property 'Pdf'
        }

        /// <summary>
        /// Test the property 'Png'
        /// </summary>
        [Fact]
        public void PngTest()
        {
            // TODO unit test for the property 'Png'
        }

        /// <summary>
        /// Test the property 'Zpl'
        /// </summary>
        [Fact]
        public void ZplTest()
        {
            // TODO unit test for the property 'Zpl'
        }
    }

}