/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ListServicePointsResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListServicePointsResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListServicePointsResponseBody
        //private ListServicePointsResponseBody instance;

        public ListServicePointsResponseBodyTests()
        {
            // TODO uncomment below to create an instance of ListServicePointsResponseBody
            //instance = new ListServicePointsResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListServicePointsResponseBody
        /// </summary>
        [Fact]
        public void ListServicePointsResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListServicePointsResponseBody
            //Assert.IsType<ListServicePointsResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Fact]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }

        /// <summary>
        /// Test the property 'Long'
        /// </summary>
        [Fact]
        public void LongTest()
        {
            // TODO unit test for the property 'Long'
        }

        /// <summary>
        /// Test the property 'ServicePoints'
        /// </summary>
        [Fact]
        public void ServicePointsTest()
        {
            // TODO unit test for the property 'ServicePoints'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }

}