/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ListShipmentRatesResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListShipmentRatesResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListShipmentRatesResponseBody
        //private ListShipmentRatesResponseBody instance;

        public ListShipmentRatesResponseBodyTests()
        {
            // TODO uncomment below to create an instance of ListShipmentRatesResponseBody
            //instance = new ListShipmentRatesResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListShipmentRatesResponseBody
        /// </summary>
        [Fact]
        public void ListShipmentRatesResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListShipmentRatesResponseBody
            //Assert.IsType<ListShipmentRatesResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Fact]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }

        /// <summary>
        /// Test the property 'InvalidRates'
        /// </summary>
        [Fact]
        public void InvalidRatesTest()
        {
            // TODO unit test for the property 'InvalidRates'
        }

        /// <summary>
        /// Test the property 'RateRequestId'
        /// </summary>
        [Fact]
        public void RateRequestIdTest()
        {
            // TODO unit test for the property 'RateRequestId'
        }

        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Fact]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }

}