/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ListCarrierPackageTypesResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCarrierPackageTypesResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCarrierPackageTypesResponseBody
        //private ListCarrierPackageTypesResponseBody instance;

        public ListCarrierPackageTypesResponseBodyTests()
        {
            // TODO uncomment below to create an instance of ListCarrierPackageTypesResponseBody
            //instance = new ListCarrierPackageTypesResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCarrierPackageTypesResponseBody
        /// </summary>
        [Fact]
        public void ListCarrierPackageTypesResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCarrierPackageTypesResponseBody
            //Assert.IsType<ListCarrierPackageTypesResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'Packages'
        /// </summary>
        [Fact]
        public void PackagesTest()
        {
            // TODO unit test for the property 'Packages'
        }
    }

}