/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ListBatchesResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListBatchesResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListBatchesResponseBody
        //private ListBatchesResponseBody instance;

        public ListBatchesResponseBodyTests()
        {
            // TODO uncomment below to create an instance of ListBatchesResponseBody
            //instance = new ListBatchesResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListBatchesResponseBody
        /// </summary>
        [Fact]
        public void ListBatchesResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListBatchesResponseBody
            //Assert.IsType<ListBatchesResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'Batches'
        /// </summary>
        [Fact]
        public void BatchesTest()
        {
            // TODO unit test for the property 'Batches'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [Fact]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
    }

}