/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing Package
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PackageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Package
        //private Package instance;

        public PackageTests()
        {
            // TODO uncomment below to create an instance of Package
            //instance = new Package();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Package
        /// </summary>
        [Fact]
        public void PackageInstanceTest()
        {
            // TODO uncomment below to test "IsType" Package
            //Assert.IsType<Package>(instance);
        }

        /// <summary>
        /// Test the property 'PackageId'
        /// </summary>
        [Fact]
        public void PackageIdTest()
        {
            // TODO unit test for the property 'PackageId'
        }

        /// <summary>
        /// Test the property 'PackageCode'
        /// </summary>
        [Fact]
        public void PackageCodeTest()
        {
            // TODO unit test for the property 'PackageCode'
        }

        /// <summary>
        /// Test the property 'ContentDescription'
        /// </summary>
        [Fact]
        public void ContentDescriptionTest()
        {
            // TODO unit test for the property 'ContentDescription'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Fact]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }

        /// <summary>
        /// Test the property 'InsuredValue'
        /// </summary>
        [Fact]
        public void InsuredValueTest()
        {
            // TODO unit test for the property 'InsuredValue'
        }

        /// <summary>
        /// Test the property 'TrackingNumber'
        /// </summary>
        [Fact]
        public void TrackingNumberTest()
        {
            // TODO unit test for the property 'TrackingNumber'
        }

        /// <summary>
        /// Test the property 'LabelMessages'
        /// </summary>
        [Fact]
        public void LabelMessagesTest()
        {
            // TODO unit test for the property 'LabelMessages'
        }

        /// <summary>
        /// Test the property 'ExternalPackageId'
        /// </summary>
        [Fact]
        public void ExternalPackageIdTest()
        {
            // TODO unit test for the property 'ExternalPackageId'
        }

        /// <summary>
        /// Test the property 'LabelDownload'
        /// </summary>
        [Fact]
        public void LabelDownloadTest()
        {
            // TODO unit test for the property 'LabelDownload'
        }

        /// <summary>
        /// Test the property 'FormDownload'
        /// </summary>
        [Fact]
        public void FormDownloadTest()
        {
            // TODO unit test for the property 'FormDownload'
        }

        /// <summary>
        /// Test the property 'PaperlessDownload'
        /// </summary>
        [Fact]
        public void PaperlessDownloadTest()
        {
            // TODO unit test for the property 'PaperlessDownload'
        }

        /// <summary>
        /// Test the property 'Sequence'
        /// </summary>
        [Fact]
        public void SequenceTest()
        {
            // TODO unit test for the property 'Sequence'
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
    }

}