/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ParseAddressRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParseAddressRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParseAddressRequestBody
        //private ParseAddressRequestBody instance;

        public ParseAddressRequestBodyTests()
        {
            // TODO uncomment below to create an instance of ParseAddressRequestBody
            //instance = new ParseAddressRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParseAddressRequestBody
        /// </summary>
        [Fact]
        public void ParseAddressRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParseAddressRequestBody
            //Assert.IsType<ParseAddressRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
    }

}