/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ShipmentStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentStatusTests
    {
        [Fact]
        public void ParameterlessConstructorSetsDefaultValue()
        {
            var testModel = new ShipmentStatus();
            Assert.Equal("pending", testModel.ToString());
        }

        [Fact]
        public void PendingTest()
        {
            var testModel = ShipmentStatus.Pending;
            Assert.Equal("pending", testModel.ToString());
        }

        [Fact]
        public void ProcessingTest()
        {
            var testModel = ShipmentStatus.Processing;
            Assert.Equal("processing", testModel.ToString());
        }

        [Fact]
        public void LabelPurchasedTest()
        {
            var testModel = ShipmentStatus.LabelPurchased;
            Assert.Equal("label_purchased", testModel.ToString());
        }

        [Fact]
        public void CancelledTest()
        {
            var testModel = ShipmentStatus.Cancelled;
            Assert.Equal("cancelled", testModel.ToString());
        }


        [Fact]
        public void CustomValueTest()
        {
            var testModel = new ShipmentStatus("a custom value");
            Assert.Equal("a custom value", testModel.ToString());
        }

        /// <summary>
        /// Test deserialize a ShipmentStatus from a string
        /// </summary>
        [Fact]
        public void CanDeserializeFromStringTest()
        {
            var testModel = JsonSerializer.Deserialize<ShipmentStatus>("\"a custom value\"");
            Assert.IsType<ShipmentStatus>(testModel);
            Assert.Equal("a custom value", testModel.ToString());
        }
    }

}