/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TaxableEntityType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaxableEntityTypeTests
    {
        [Fact]
        public void ParameterlessConstructorSetsDefaultValue()
        {
            var testModel = new TaxableEntityType();
            Assert.Equal("shipper", testModel.ToString());
        }

        [Fact]
        public void ShipperTest()
        {
            var testModel = TaxableEntityType.Shipper;
            Assert.Equal("shipper", testModel.ToString());
        }

        [Fact]
        public void RecipientTest()
        {
            var testModel = TaxableEntityType.Recipient;
            Assert.Equal("recipient", testModel.ToString());
        }

        [Fact]
        public void IorTest()
        {
            var testModel = TaxableEntityType.Ior;
            Assert.Equal("ior", testModel.ToString());
        }


        [Fact]
        public void CustomValueTest()
        {
            var testModel = new TaxableEntityType("a custom value");
            Assert.Equal("a custom value", testModel.ToString());
        }

        /// <summary>
        /// Test deserialize a TaxableEntityType from a string
        /// </summary>
        [Fact]
        public void CanDeserializeFromStringTest()
        {
            var testModel = JsonSerializer.Deserialize<TaxableEntityType>("\"a custom value\"");
            Assert.IsType<TaxableEntityType>(testModel);
            Assert.Equal("a custom value", testModel.ToString());
        }
    }

}