/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateShipmentsTagsShipmentsTagsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateShipmentsTagsShipmentsTagsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateShipmentsTagsShipmentsTagsInner
        //private UpdateShipmentsTagsShipmentsTagsInner instance;

        public UpdateShipmentsTagsShipmentsTagsInnerTests()
        {
            // TODO uncomment below to create an instance of UpdateShipmentsTagsShipmentsTagsInner
            //instance = new UpdateShipmentsTagsShipmentsTagsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateShipmentsTagsShipmentsTagsInner
        /// </summary>
        [Fact]
        public void UpdateShipmentsTagsShipmentsTagsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateShipmentsTagsShipmentsTagsInner
            //Assert.IsType<UpdateShipmentsTagsShipmentsTagsInner>(instance);
        }

        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Fact]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }

}