/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using ShipEngineSDK.Client;
using ShipEngineSDK.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace ShipEngineSDK.Test.Model
{
    /// <summary>
    ///  Class for testing VoidLabelResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VoidLabelResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VoidLabelResponseBody
        //private VoidLabelResponseBody instance;

        public VoidLabelResponseBodyTests()
        {
            // TODO uncomment below to create an instance of VoidLabelResponseBody
            //instance = new VoidLabelResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VoidLabelResponseBody
        /// </summary>
        [Fact]
        public void VoidLabelResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" VoidLabelResponseBody
            //Assert.IsType<VoidLabelResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'Approved'
        /// </summary>
        [Fact]
        public void ApprovedTest()
        {
            // TODO unit test for the property 'Approved'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'ReasonCode'
        /// </summary>
        [Fact]
        public void ReasonCodeTest()
        {
            // TODO unit test for the property 'ReasonCode'
        }
    }

}