/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using ShipEngineSDK.Client;
// uncomment below to import models
using ShipEngineSDK.Model;
using ShipEngineTest;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Reflection;
using Xunit;

namespace ShipEngineSDK.Test.Api
{
    /// <summary>
    ///  Class for testing ManifestsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ManifestsApiTests : IDisposable
    {
        private ShipEngine instance;

        public ManifestsApiTests()
        {
            var config = new Config("test-key");
            var mockShipEngineFixture = new MockShipEngineFixture(config);
            instance = mockShipEngineFixture.ShipEngine;
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManifestsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ManifestsApi
            //Assert.IsType<ManifestsApi>(instance);
        }

        /// <summary>
        /// Test CreateManifest
        /// </summary>
        [Fact]
        public void CreateManifestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateManifestRequestBody createManifestRequestBody = null;
            //var response = instance.CreateManifest(createManifestRequestBody);
            //Assert.IsType<CreateManifestResponseBody>(response);
        }

        /// <summary>
        /// Test GetManifestById
        /// </summary>
        [Fact]
        public void GetManifestByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string manifestId = null;
            //var response = instance.GetManifestById(manifestId);
            //Assert.IsType<GetManifestByIdResponseBody>(response);
        }

        /// <summary>
        /// Test GetManifestRequestById
        /// </summary>
        [Fact]
        public void GetManifestRequestByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string manifestRequestId = null;
            //var response = instance.GetManifestRequestById(manifestRequestId);
            //Assert.IsType<CreateManifestResponseBody>(response);
        }

        /// <summary>
        /// Test ListManifests
        /// </summary>
        [Fact]
        public void ListManifestsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string warehouseId = null;
            //DateTime? shipDateStart = null;
            //DateTime? shipDateEnd = null;
            //DateTime? createdAtStart = null;
            //DateTime? createdAtEnd = null;
            //string carrierId = null;
            //int? page = null;
            //int? pageSize = null;
            //List<string> labelIds = null;
            //var response = instance.ListManifests(warehouseId, shipDateStart, shipDateEnd, createdAtStart, createdAtEnd, carrierId, page, pageSize, labelIds);
            //Assert.IsType<ListManifestsResponseBody>(response);
        }
    }
}