/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using ShipEngineSDK.Client;
// uncomment below to import models
using ShipEngineSDK.Model;
using ShipEngineTest;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Reflection;
using Xunit;

namespace ShipEngineSDK.Test.Api
{
    /// <summary>
    ///  Class for testing PackageTypesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PackageTypesApiTests : IDisposable
    {
        private ShipEngine instance;

        public PackageTypesApiTests()
        {
            var config = new Config("test-key");
            var mockShipEngineFixture = new MockShipEngineFixture(config);
            instance = mockShipEngineFixture.ShipEngine;
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PackageTypesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PackageTypesApi
            //Assert.IsType<PackageTypesApi>(instance);
        }

        /// <summary>
        /// Test CreatePackageType
        /// </summary>
        [Fact]
        public void CreatePackageTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreatePackageTypeRequestBody createPackageTypeRequestBody = null;
            //var response = instance.CreatePackageType(createPackageTypeRequestBody);
            //Assert.IsType<CreatePackageTypeResponseBody>(response);
        }

        /// <summary>
        /// Test DeletePackageType
        /// </summary>
        [Fact]
        public void DeletePackageTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string packageId = null;
            //var response = instance.DeletePackageType(packageId);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test GetPackageTypeById
        /// </summary>
        [Fact]
        public void GetPackageTypeByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string packageId = null;
            //var response = instance.GetPackageTypeById(packageId);
            //Assert.IsType<GetPackageTypeByIdResponseBody>(response);
        }

        /// <summary>
        /// Test ListPackageTypes
        /// </summary>
        [Fact]
        public void ListPackageTypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListPackageTypes();
            //Assert.IsType<ListPackageTypesResponseBody>(response);
        }

        /// <summary>
        /// Test UpdatePackageType
        /// </summary>
        [Fact]
        public void UpdatePackageTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string packageId = null;
            //UpdatePackageTypeRequestBody updatePackageTypeRequestBody = null;
            //var response = instance.UpdatePackageType(packageId, updatePackageTypeRequestBody);
            //Assert.IsType<string>(response);
        }
    }
}