// <auto-generated />
// DO NOT MODIFY THIS FILE

// Changes can be made in a corresponding partial file, or by changing
// the template in <root>/generation/templates and generating the class again.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;

namespace ShipEngineSDK.Model;

/// <summary>
/// Estimated import charges for commercial invoices for international shipments. 
/// </summary>
public partial class EstimatedImportCharges
{

    /// <summary>
    /// Estimated import duties.
    /// </summary>
    /// <value>Estimated import duties.</value>
    [JsonPropertyName("duties"), JsonPropertyOrder(1)]
    public MonetaryValue? Duties { get; set; }

    /// <summary>
    /// Estimated import taxes.
    /// </summary>
    /// <value>Estimated import taxes.</value>
    [JsonPropertyName("taxes"), JsonPropertyOrder(2)]
    public MonetaryValue? Taxes { get; set; }


    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class EstimatedImportCharges {\n");
#pragma warning disable CS0612 // Type or member is obsolete
        sb.Append("  Duties: ").Append(Duties).Append("\n");
        sb.Append("  Taxes: ").Append(Taxes).Append("\n");
#pragma warning restore CS0612 // Type or member is obsolete
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson(JsonSerializerOptions options)
    {
        return JsonSerializer.Serialize(this, options);
    }

}