/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;

namespace ShipEngineSDK.Model;

/// <summary>
/// GetServicePointsRequestBodyProvidersInner
/// </summary>
//[DataContract(Name = "get_service_points_request_body_providers_inner")]
public partial class GetServicePointsRequestBodyProvidersInner
{

    /// <summary>
    /// Uniquely identifies a carrier connection
    /// </summary>
    /// <value>Uniquely identifies a carrier connection</value>
    /// <example>
    /// se-123456
    /// </example>
    [JsonPropertyName("carrier_id")]
    public string CarrierId { get; set; }

    /// <summary>
    /// Gets or Sets ServiceCode
    /// </summary>
    [JsonPropertyName("service_code")]
    public List<string> ServiceCode { get; set; }


    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        StringBuilder sb = new StringBuilder();
        sb.Append("class GetServicePointsRequestBodyProvidersInner {\n");
        sb.Append("  CarrierId: ").Append(CarrierId).Append("\n");
        sb.Append("  ServiceCode: ").Append(ServiceCode).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson(JsonSerializerOptions options)
    {
        return JsonSerializer.Serialize(this, options);
    }

}