// <auto-generated />
// DO NOT MODIFY THIS FILE

// Changes can be made in a corresponding partial file, or by changing
// the template in <root>/generation/templates and generating the class again.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;

namespace ShipEngineSDK.Model;

/// <summary>
/// A modify batch object
/// </summary>
public partial class ModifyBatch
{

    /// <summary>
    /// Array of Rate IDs to be modifed on the batch
    /// </summary>
    /// <value>Array of Rate IDs to be modifed on the batch</value>
    [JsonPropertyName("rate_ids"), JsonPropertyOrder(1)]
    public List<string>? RateIds { get; set; }

    /// <summary>
    /// The Shipment Ids to be modified on the batch
    /// </summary>
    /// <value>The Shipment Ids to be modified on the batch</value>
    [JsonPropertyName("shipment_ids"), JsonPropertyOrder(2)]
    public List<string>? ShipmentIds { get; set; }


    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ModifyBatch {\n");
#pragma warning disable CS0612 // Type or member is obsolete
        sb.Append("  RateIds: ").Append(RateIds).Append("\n");
        sb.Append("  ShipmentIds: ").Append(ShipmentIds).Append("\n");
#pragma warning restore CS0612 // Type or member is obsolete
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson(JsonSerializerOptions options)
    {
        return JsonSerializer.Serialize(this, options);
    }

}