/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;

namespace ShipEngineSDK.Model;

/// <summary>
/// A purchase label without shipment resource
/// </summary>
public partial class PurchaseLabelWithoutShipment
{

    /// <summary>
    /// The display format that the label should be shown in.  CLOVUS
    /// </summary>
    /// <value>The display format that the label should be shown in.</value>
    [JsonPropertyName("display_scheme")]
    public DisplayScheme? DisplayScheme { get; set; }
    /// <summary>
    /// Gets or Sets LabelDownloadType  CLOVUS
    /// </summary>
    [JsonPropertyName("label_download_type")]
    public LabelDownloadType? LabelDownloadType { get; set; }
    /// <summary>
    /// Gets or Sets LabelFormat  CLOVUS
    /// </summary>
    [JsonPropertyName("label_format")]
    public LabelFormat? LabelFormat { get; set; }
    /// <summary>
    /// Gets or Sets LabelLayout  CLOVUS
    /// </summary>
    [JsonPropertyName("label_layout")]
    public LabelLayout? LabelLayout { get; set; }
    /// <summary>
    /// Gets or Sets ValidateAddress  CLOVUS
    /// </summary>
    [JsonPropertyName("validate_address")]
    public ValidateAddress? ValidateAddress { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        StringBuilder sb = new StringBuilder();
        sb.Append("class PurchaseLabelWithoutShipment {\n");
#pragma warning disable CS0612 // Type or member is obsolete
        sb.Append("  DisplayScheme: ").Append(DisplayScheme).Append("\n");
        sb.Append("  LabelDownloadType: ").Append(LabelDownloadType).Append("\n");
        sb.Append("  LabelFormat: ").Append(LabelFormat).Append("\n");
        sb.Append("  LabelLayout: ").Append(LabelLayout).Append("\n");
        sb.Append("  ValidateAddress: ").Append(ValidateAddress).Append("\n");
#pragma warning restore CS0612 // Type or member is obsolete
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson(JsonSerializerOptions options)
    {
        return JsonSerializer.Serialize(this, options);
    }

}