/*
 * ShipEngine API
 *
 * The version of the OpenAPI document: 1.1.202406212006
 * Contact: sales@shipengine.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;

namespace ShipEngineSDK.Model;

/// <summary>
/// The resource to return a redirect URL to.
/// </summary>
/// <value>The resource to return a redirect URL to.</value>
[JsonConverter(typeof(RedirectJsonConverter))]
public class Redirect
{
    private readonly string _value;

    /// <summary>
    /// Create a new instance of Redirect with a predefined value.
    /// </summary>
    internal Redirect()
    {
        _value = "shipengine-dashboard";
    }

    /// <summary>
    /// Create a new instance of Redirect with a custom value.
    /// </summary>
    /// <param name="value">The value of the Redirect</param>
    /// <remarks>
    /// You can send a custom value to the API using this constructor, but the API most likely won't know what to do with it.
    /// You should use the predefined values returned by the static properties of this class unless you know that the value is value.
    /// </remarks>
    public Redirect(string value)
    {
        _value = value;
    }

    /// <summary>
    /// Enum ShipengineDashboard for value: shipengine-dashboard
    /// </summary>
    public static Redirect ShipengineDashboard { get; } = new("shipengine-dashboard");


    /// <summary>
    /// Get a string representation of the current value
    /// </summary>
    public override string ToString() => _value;

    /// <summary>
    /// Get whether this instance is equal to another instance
    /// </summary>
    public override bool Equals(object? obj) =>
        obj is Redirect other && _value == other._value;
}

internal class RedirectJsonConverter : JsonConverter<Redirect>
{
    public override Redirect? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? new Redirect(reader.GetString()!) : null;

    public override void Write(Utf8JsonWriter writer, Redirect value, JsonSerializerOptions options) =>
        writer.WriteStringValue(value.ToString());

    public override bool CanConvert(Type typeToConvert) =>
        typeToConvert == typeof(Redirect);
}