// <auto-generated />
// DO NOT MODIFY THIS FILE

// Changes can be made in a corresponding partial file, or by changing
// the template in <root>/generation/templates and generating the class again.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;

namespace ShipEngineSDK.Model;

/// <summary>
/// The possible ups pickup type values
/// </summary>
/// <value>The possible ups pickup type values</value>
[JsonConverter(typeof(UpsPickupTypeJsonConverter))]
public class UpsPickupType
{
    private readonly string _value;

    /// <summary>
    /// Create a new instance of UpsPickupType with a predefined value.
    /// </summary>
    internal UpsPickupType()
    {
        _value = "daily_pickup";
    }

    /// <summary>
    /// Create a new instance of UpsPickupType with a custom value.
    /// </summary>
    /// <param name="value">The value of the UpsPickupType</param>
    /// <remarks>
    /// You can send a custom value to the API using this constructor, but the API most likely won't know what to do with it.
    /// You should use the predefined values returned by the static properties of this class unless you know that the value is value.
    /// </remarks>
    public UpsPickupType(string value)
    {
        _value = value;
    }

    /// <summary>
    /// Enum DailyPickup for value: daily_pickup
    /// </summary>
    public static UpsPickupType DailyPickup { get; } = new("daily_pickup");


    /// <summary>
    /// Enum OccasionalPickup for value: occasional_pickup
    /// </summary>
    public static UpsPickupType OccasionalPickup { get; } = new("occasional_pickup");


    /// <summary>
    /// Enum CustomerCounter for value: customer_counter
    /// </summary>
    public static UpsPickupType CustomerCounter { get; } = new("customer_counter");


    /// <summary>
    /// Get a string representation of the current value
    /// </summary>
    public override string ToString() => _value;

    /// <summary>
    /// Get whether this instance is equal to another instance
    /// </summary>
    public override bool Equals(object? obj) =>
        obj is UpsPickupType other && _value == other._value;

    /// <summary>
    /// Get the hash code of the object
    /// </summary>
    public override int GetHashCode() => _value.GetHashCode();
}

internal class UpsPickupTypeJsonConverter : JsonConverter<UpsPickupType>
{
    public override UpsPickupType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? new UpsPickupType(reader.GetString()!) : null;

    public override void Write(Utf8JsonWriter writer, UpsPickupType value, JsonSerializerOptions options) =>
        writer.WriteStringValue(value.ToString());

    public override bool CanConvert(Type typeToConvert) =>
        typeToConvert == typeof(UpsPickupType);
}